
set_property PACKAGE_PIN W5 [get_ports {pin_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_clk}]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {pin_clk}] 

## switches
set_property PACKAGE_PIN V17 [get_ports {pin_sw[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {pin_sw[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {pin_sw[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {pin_sw[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {pin_sw[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {pin_sw[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {pin_sw[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {pin_sw[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[7]}]
set_property PACKAGE_PIN V2 [get_ports {pin_sw[8]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[8]}]
set_property PACKAGE_PIN T3 [get_ports {pin_sw[9]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[9]}]
set_property PACKAGE_PIN T2 [get_ports {pin_sw[10]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[10]}]
set_property PACKAGE_PIN R3 [get_ports {pin_sw[11]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {pin_sw[12]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[12]}]
set_property PACKAGE_PIN U1 [get_ports {pin_sw[13]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[13]}]
set_property PACKAGE_PIN T1 [get_ports {pin_sw[14]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {pin_sw[15]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_sw[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {pin_led[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[0]}]
set_property PACKAGE_PIN E19 [get_ports {pin_led[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[1]}]
set_property PACKAGE_PIN U19 [get_ports {pin_led[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[2]}]
set_property PACKAGE_PIN V19 [get_ports {pin_led[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[3]}]
set_property PACKAGE_PIN W18 [get_ports {pin_led[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[4]}]
set_property PACKAGE_PIN U15 [get_ports {pin_led[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[5]}]
set_property PACKAGE_PIN U14 [get_ports {pin_led[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[6]}]
set_property PACKAGE_PIN V14 [get_ports {pin_led[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[7]}]
set_property PACKAGE_PIN V13 [get_ports {pin_led[8]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[8]}]
set_property PACKAGE_PIN V3 [get_ports {pin_led[9]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[9]}]
set_property PACKAGE_PIN W3 [get_ports {pin_led[10]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[10]}]
set_property PACKAGE_PIN U3 [get_ports {pin_led[11]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[11]}]
set_property PACKAGE_PIN P3 [get_ports {pin_led[12]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[12]}]
set_property PACKAGE_PIN N3 [get_ports {pin_led[13]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[13]}]
set_property PACKAGE_PIN P1 [get_ports {pin_led[14]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[14]}]
set_property PACKAGE_PIN L1 [get_ports {pin_led[15]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_led[15]}]

## Button
set_property PACKAGE_PIN U18 [get_ports {pin_btn_c}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_btn_c}]
# set_property PACKAGE_PIN T18 [get_ports {pin_btn_u}]
# set_property IOSTANDARD LVCMOS33 [get_ports {pin_btn_u}]
# set_property PACKAGE_PIN W19 [get_ports {pin_btn_l}]
# set_property IOSTANDARD LVCMOS33 [get_ports {pin_btn_l}]
# set_property PACKAGE_PIN T17 [get_ports {pin_btn_r}]
# set_property IOSTANDARD LVCMOS33 [get_ports {pin_btn_r}]
# set_property PACKAGE_PIN U17 [get_ports {pin_btn_d}]
# set_property IOSTANDARD LVCMOS33 [get_ports {pin_btn_d}]

# segment display
set_property PACKAGE_PIN W7 [get_ports {pin_seg[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {pin_seg[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {pin_seg[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {pin_seg[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {pin_seg[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {pin_seg[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {pin_seg[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[6]}]
set_property PACKAGE_PIN V7 [get_ports {pin_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg[7]}] 

#segment select
set_property PACKAGE_PIN U2 [get_ports {pin_seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg_sel[0]}]
set_property PACKAGE_PIN U4 [get_ports {pin_seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg_sel[1]}]
set_property PACKAGE_PIN V4 [get_ports {pin_seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg_sel[2]}]
set_property PACKAGE_PIN W4 [get_ports {pin_seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_seg_sel[3]}]
